# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/COLLEGE/homework/hit-coa-lab/lab1/lab1.srcs/sources_1/ip/mr_bram/mr_bram.xci
# IP: The module: 'mr_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COLLEGE/homework/hit-coa-lab/lab1/lab1.gen/sources_1/ip/mr_bram/mr_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mr_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/COLLEGE/homework/hit-coa-lab/lab1/lab1.srcs/sources_1/ip/mr_bram/mr_bram.xci
# IP: The module: 'mr_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/COLLEGE/homework/hit-coa-lab/lab1/lab1.gen/sources_1/ip/mr_bram/mr_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mr_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
